@baseURL = http://localhost:3000

# # Test LOGIN 
# POST  {{ baseURL }}/api/auth
# Accept: application/json
# Content-Type: application/json
# Type: LOGIN

# {
#   "username": "ujklm23",
#   "password": "rahasia"
# }

POST {{ baseURL }}/api/auth 
Accept: application/json
Content-Type: application/json
Type: REGISTER

{
  "username": "joy",
  "nama": "Joya Wondra",
  "password": "rahasia",
  "alamat": "St. Fushi R 24 ",
  "nomor_telepon": "+32474756756"
}